window.ResumeAPI = window.ResumeAPI || {};
window.ResumeAPI.skills = [
  "NestJS",
  "Node.js",
  "TypeScript",
  "Prisma",
  "TypeORM",
  "Socket.io",
  "Redis",
  "Redis Cluster",
  "MySQL",
  "MariaDB",
  "Golang",
  "Python",
  "PHP",
  "AWS",
  "Supabase",
  "Coolify",
  "Docker",
  "Kubernetes",
  "CI/CD Pipeline",
  "Claude Code Agent",
  "AI Orchestration (Parallel)",
  "Harness Skill",
  "Linux",
  "Apache",
  "Nginx"
];
